# infrastructure.yaml (CloudFormation template)

AWSTemplateFormatVersion: '2010-09-09'
Description: Static Web Application Infrastructure

Parameters:
  BucketName:
    Type: String
    Description: static-site
  CertificateArn:
    Type: String
    Description: arn:aws:acm:us-east-1:123456789012:certificate/abcdef12-3456-7890-abcd-ef1234567890
  DomainName:
    Type: String
    Description: static-site.local

Resources:
  # S3 Bucket for hosting static content
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html

  # CloudFront distribution
  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt MyS3Bucket.DomainName
            Id: MyS3Origin
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: MyS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only

  # Route 53 DNS record
  MyDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: example.com.
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt MyCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

# Security groups, NACLs, and other configurations go here
# Automated tests (e.g., Lambda functions) can be added as well
